name: hexa_challenge
description: Jogo de pênalti interescolar — Copa do Mundo 2026

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.3.1
  confetti: ^0.7.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  socket_io_client: ^2.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
